#!/bin/bash

pkgbox::prep() {
    # fetch, patch, etc
}

pkgbox::build() {
    # make, cmake, gcc, etc
}

pkgbox::install() {
    # "install" whatever needs to be installed into ...
    # whatever is installed will be stored in the layer diff
}

pkgbox::cleanup() {
    # additional cleanup , if needed
}
